### PR TITLE
Fixed encryption settings

### PR DESCRIPTION
**Pull request by Sliim**

### CODE REVIEW

**Comment by Sliim** [comment]
Maybe some other configuration settings are affected.. I only tested for encryption..

**Comment by damm** [comment]
well in that block it's only for encryption settings.  So it should be safe.

**Comment by damm** [comment]
encrypt_with({"engine" => "OpenSSL", "settings" => { "encryption.password" => "kitchen", "encrypt\
ion.base64" => "true", "encryption.salt" => "true"}})

That has worked and there's a test for it.  So you just wanted everything to prepended encryption for ease?

**Comment by damm** [comment]
Yeah the default test fails because of this; I kinda designed it this way not knowing that all keys should be under encryption.  I hate making assumptions like that.

Produces 
```ruby
encrypt_with OpenSSL do |encryption|
    encryption.encryption.password = "kitchen"
    encryption.encryption.base64 = "true"
    encryption.encryption.salt = "true"
  end
```

So we could move to what you have there if you want to make life easier for people.  But our tests should be updated to match?

**Comment by Sliim** [comment]
Oh ok, my bad.. I misuse the settings model. I will use `encryption` in my keys, do not change your implementation it's good ;).

> I kinda designed it this way not knowing that all keys should be under encryption. I hate making assumptions like that.

:+1:

**Pull request closed without merging**
